/**
 * POST /api/spirit-animal — Spirit animal guide creation flow.
 *
 * Two modes of operation:
 *  1. No body (or empty body) — returns 6 conversational quiz questions generated by Gemini.
 *  2. Body contains `answers: { question, answer }[]` — evaluates answers, picks the best-fit
 *     spirit animal and a variant from the curated set, and returns { animal, description, svg }.
 *
 * Each animal has multiple SVG variants so "Try again" can produce visibly different outputs.
 * Gemini also picks a variant index so repeated evaluations feel different.
 */

import { Router, type IRouter } from "express";
import { z } from "zod";
import { ai } from "@workspace/integrations-gemini-ai";

const router: IRouter = Router();

const MODEL = "gemini-2.5-flash";

// ---------------------------------------------------------------------------
// Pre-defined SVG templates — ultra-minimalist, white stroke, 40×40 viewBox
// Each animal has 2–3 distinct geometric representations.
// ---------------------------------------------------------------------------

const SVG_VARIANTS: Record<string, string[]> = {
  fox: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><polygon points="8,32 20,10 32,32" /><polygon points="8,32 14,22 20,28" /><polygon points="32,32 26,22 20,28" /><circle cx="20" cy="22" r="2" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="16" y1="26" x2="12" y2="30" /><line x1="24" y1="26" x2="28" y2="30" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><circle cx="20" cy="18" r="8" /><polygon points="13,13 10,8 17,12" /><polygon points="27,13 30,8 23,12" /><circle cx="17" cy="17" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="17" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><path d="M17,22 Q20,24 23,22" /><path d="M14,30 Q16,24 20,26 Q24,24 26,30" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="20" rx="9" ry="8" /><polygon points="11,14 7,9 15,13" /><polygon points="29,14 33,9 25,13" /><circle cx="17" cy="19" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="19" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><path d="M18,24 Q20,26 22,24" /><path d="M6,26 Q10,20 14,22" /><line x1="16" y1="28" x2="14" y2="34" /><line x1="24" y1="28" x2="26" y2="34" /></svg>`,
  ],
  owl: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="22" rx="10" ry="12" /><circle cx="16" cy="19" r="3" /><circle cx="24" cy="19" r="3" /><circle cx="16" cy="19" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="24" cy="19" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><polygon points="18,24 20,26 22,24" /><line x1="10" y1="14" x2="14" y2="18" /><line x1="30" y1="14" x2="26" y2="18" /><line x1="12" y1="30" x2="10" y2="34" /><line x1="28" y1="30" x2="30" y2="34" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><rect x="12" y="10" width="16" height="20" rx="8" /><circle cx="17" cy="18" r="3.5" /><circle cx="23" cy="18" r="3.5" /><circle cx="17" cy="18" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="18" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><polygon points="18,23 20,25 22,23" /><line x1="12" y1="10" x2="9" y2="7" /><line x1="28" y1="10" x2="31" y2="7" /><polygon points="6,28 14,24 14,32" /><polygon points="34,28 26,24 26,32" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M10,32 Q10,14 20,12 Q30,14 30,32 Z" /><circle cx="16" cy="20" r="4" /><circle cx="24" cy="20" r="4" /><circle cx="16" cy="20" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="24" cy="20" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><polygon points="18,25 20,28 22,25" /><line x1="10" y1="14" x2="7" y2="10" /><line x1="30" y1="14" x2="33" y2="10" /></svg>`,
  ],
  wolf: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><polygon points="20,8 28,16 24,28 16,28 12,16" /><polygon points="14,10 20,8 18,15" /><polygon points="26,10 20,8 22,15" /><circle cx="17" cy="18" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="18" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="17" y1="22" x2="23" y2="22" /><line x1="16" y1="28" x2="14" y2="34" /><line x1="24" y1="28" x2="26" y2="34" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M10,30 Q12,18 20,14 Q28,18 30,30" /><polygon points="12,16 9,10 16,14" /><polygon points="28,16 31,10 24,14" /><circle cx="17" cy="20" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="20" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><path d="M18,24 Q20,26 22,24" /><line x1="14" y1="30" x2="12" y2="36" /><line x1="26" y1="30" x2="28" y2="36" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="20" rx="9" ry="10" /><polygon points="13,14 9,9 17,13" /><polygon points="27,14 31,9 23,13" /><circle cx="17" cy="18" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="18" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><path d="M17,23 Q20,25 23,23" /><path d="M20,30 Q26,34 30,30" /><line x1="15" y1="30" x2="14" y2="36" /><line x1="25" y1="30" x2="26" y2="36" /></svg>`,
  ],
  deer: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="22" rx="7" ry="9" /><circle cx="20" cy="13" r="5" /><line x1="14" y1="10" x2="10" y2="6" /><line x1="10" y1="6" x2="8" y2="10" /><line x1="10" y1="6" x2="12" y2="10" /><line x1="26" y1="10" x2="30" y2="6" /><line x1="30" y1="6" x2="28" y2="10" /><line x1="30" y1="6" x2="32" y2="10" /><circle cx="18" cy="13" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="22" cy="13" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="16" y1="30" x2="15" y2="36" /><line x1="24" y1="30" x2="25" y2="36" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M14,30 Q14,22 20,20 Q26,22 26,30" /><circle cx="20" cy="14" r="6" /><line x1="16" y1="10" x2="10" y2="4" /><line x1="10" y1="4" x2="8" y2="8" /><line x1="10" y1="4" x2="13" y2="7" /><line x1="24" y1="10" x2="30" y2="4" /><line x1="30" y1="4" x2="32" y2="8" /><line x1="30" y1="4" x2="27" y2="7" /><circle cx="18" cy="13" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="22" cy="13" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="16" y1="30" x2="14" y2="36" /><line x1="24" y1="30" x2="26" y2="36" /></svg>`,
  ],
  bear: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="24" rx="11" ry="10" /><circle cx="20" cy="14" r="7" /><circle cx="13" cy="10" r="3" /><circle cx="27" cy="10" r="3" /><circle cx="17" cy="13" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="13" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><ellipse cx="20" cy="17" rx="3" ry="2" /><line x1="12" y1="32" x2="11" y2="37" /><line x1="28" y1="32" x2="29" y2="37" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><circle cx="20" cy="20" r="12" /><circle cx="13" cy="10" r="4" /><circle cx="27" cy="10" r="4" /><circle cx="17" cy="18" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="18" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><ellipse cx="20" cy="22" rx="4" ry="3" /><line x1="10" y1="30" x2="8" y2="36" /><line x1="30" y1="30" x2="32" y2="36" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="14" width="22" height="18" rx="11" /><circle cx="20" cy="12" r="8" /><circle cx="13" cy="8" r="3.5" /><circle cx="27" cy="8" r="3.5" /><circle cx="17" cy="11" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="11" r="1.5" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="20" cy="15" r="2" fill="rgba(255,255,255,0.5)" stroke="none" /><line x1="13" y1="32" x2="11" y2="37" /><line x1="27" y1="32" x2="29" y2="37" /></svg>`,
  ],
  hawk: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="18" rx="5" ry="8" /><polygon points="6,20 20,14 20,22" /><polygon points="34,20 20,14 20,22" /><circle cx="18" cy="14" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><polygon points="18,22 20,26 22,22" /><line x1="18" y1="26" x2="16" y2="32" /><line x1="22" y1="26" x2="24" y2="32" /><line x1="16" y1="32" x2="14" y2="34" /><line x1="24" y1="32" x2="26" y2="34" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><polygon points="20,6 26,16 20,22 14,16" /><polygon points="4,24 14,16 20,22" /><polygon points="36,24 26,16 20,22" /><circle cx="18" cy="14" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><polygon points="18,22 20,28 22,22" /><line x1="18" y1="28" x2="16" y2="34" /><line x1="22" y1="28" x2="24" y2="34" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20,8 L20,26" /><path d="M4,18 Q12,12 20,14 Q28,12 36,18" /><circle cx="19" cy="12" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><polygon points="17,26 20,30 23,26" /><line x1="17" y1="30" x2="15" y2="36" /><line x1="23" y1="30" x2="25" y2="36" /><path d="M8,22 Q12,26 14,24" /><path d="M32,22 Q28,26 26,24" /></svg>`,
  ],
  dolphin: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M8,22 Q14,14 26,18 Q32,20 34,18" /><path d="M34,18 Q36,14 32,12" /><path d="M26,18 Q28,12 24,10" /><path d="M8,22 Q6,26 10,28 Q14,26 8,22" /><circle cx="30" cy="18" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><path d="M20,16 Q22,22 18,24" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M6,24 Q12,16 22,18 Q30,20 34,16 Q36,12 32,10" /><path d="M22,18 Q24,12 20,10" /><path d="M6,24 Q4,28 8,30 Q12,28 6,24" /><circle cx="30" cy="16" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><path d="M18,34 Q22,28 26,30 Q28,34 24,36" /></svg>`,
  ],
  cat: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="22" rx="9" ry="10" /><circle cx="20" cy="14" r="6" /><polygon points="14,10 12,6 18,10" /><polygon points="26,10 28,6 22,10" /><circle cx="17" cy="13" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="13" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="16" y1="16" x2="10" y2="15" /><line x1="16" y1="17" x2="10" y2="18" /><line x1="24" y1="16" x2="30" y2="15" /><line x1="24" y1="17" x2="30" y2="18" /><path d="M26,32 Q30,28 32,32" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><rect x="12" y="14" width="16" height="18" rx="8" /><circle cx="20" cy="12" r="7" /><polygon points="13,8 10,4 17,8" /><polygon points="27,8 30,4 23,8" /><circle cx="17" cy="12" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="12" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="15" y1="15" x2="9" y2="14" /><line x1="15" y1="16.5" x2="9" y2="17" /><line x1="25" y1="15" x2="31" y2="14" /><line x1="25" y1="16.5" x2="31" y2="17" /><path d="M24,34 Q28,30 30,34" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M11,32 Q11,18 20,16 Q29,18 29,32" /><circle cx="20" cy="13" r="6" /><polygon points="14,9 11,5 17,9" /><polygon points="26,9 29,5 23,9" /><circle cx="17" cy="12" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="23" cy="12" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="15" y1="15" x2="9" y2="14" /><line x1="15" y1="16" x2="9" y2="17" /><line x1="25" y1="15" x2="31" y2="14" /><line x1="25" y1="16" x2="31" y2="17" /><path d="M28,36 Q32,30 34,34" /></svg>`,
  ],
  rabbit: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="20" cy="24" rx="8" ry="9" /><circle cx="20" cy="16" r="5" /><ellipse cx="15" cy="8" rx="2.5" ry="5" /><ellipse cx="25" cy="8" rx="2.5" ry="5" /><circle cx="18" cy="15" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="22" cy="15" r="1" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="20" cy="18" r="1.2" fill="rgba(255,255,255,0.4)" stroke="none" /><line x1="16" y1="32" x2="15" y2="36" /><line x1="24" y1="32" x2="25" y2="36" /><ellipse cx="26" cy="27" rx="3" ry="2" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><circle cx="20" cy="22" r="9" /><circle cx="20" cy="14" r="6" /><ellipse cx="14" cy="7" rx="3" ry="6" /><ellipse cx="26" cy="7" rx="3" ry="6" /><circle cx="18" cy="13" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><circle cx="22" cy="13" r="1.2" fill="rgba(255,255,255,0.8)" stroke="none" /><ellipse cx="20" cy="17" rx="2" ry="1.5" fill="rgba(255,255,255,0.4)" stroke="none" /><line x1="15" y1="30" x2="13" y2="36" /><line x1="25" y1="30" x2="27" y2="36" /><ellipse cx="27" cy="26" rx="4" ry="2.5" /></svg>`,
  ],
  snake: [
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M8,32 Q8,20 14,18 Q20,16 20,10 Q20,6 24,8 Q28,10 26,14 Q24,18 20,20 Q14,22 14,30 Q14,36 20,36 Q26,36 28,32" /><circle cx="24" cy="8" r="2" /><circle cx="23" cy="7" r="0.8" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="24" y1="10" x2="22" y2="12" /><line x1="24" y1="10" x2="26" y2="12" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M32,8 Q36,16 28,20 Q20,24 20,30 Q20,36 14,36 Q8,36 8,30 Q8,24 16,22 Q24,20 24,14 Q24,8 20,8" /><circle cx="20" cy="8" r="2.5" /><circle cx="19" cy="7" r="0.8" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="20" y1="10.5" x2="18" y2="12.5" /><line x1="20" y1="10.5" x2="22" y2="12.5" /></svg>`,
    `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="rgba(255,255,255,0.8)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20,34 Q12,34 12,28 Q12,22 20,20 Q28,18 28,12 Q28,6 22,6 Q16,6 16,12" /><circle cx="22" cy="6" r="2" /><circle cx="21.2" cy="5" r="0.8" fill="rgba(255,255,255,0.8)" stroke="none" /><line x1="22" y1="8" x2="20" y2="10" /><line x1="22" y1="8" x2="24" y2="10" /><ellipse cx="20" cy="34" rx="6" ry="3" /></svg>`,
  ],
};

const ANIMALS = Object.keys(SVG_VARIANTS);

// Helper: pick a variant for an animal.
// `seed` is clamped to valid bounds so negative/non-integer values from Gemini are safe.
function pickVariant(animal: string, seed?: number): string {
  const variants = SVG_VARIANTS[animal] ?? SVG_VARIANTS.fox;
  if (seed === undefined || !Number.isFinite(seed)) {
    return variants[Math.floor(Math.random() * variants.length)];
  }
  const idx = Math.abs(Math.floor(seed)) % variants.length;
  return variants[idx];
}

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

const answerSchema = z.object({
  question: z.string().max(500),
  answer: z.string().max(1000),
});

const requestSchema = z.object({
  answers: z.array(answerSchema).max(3).optional(),
});

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

router.post("/spirit-animal", async (req, res) => {
  const parsed = requestSchema.safeParse(req.body ?? {});
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid request body" });
    return;
  }

  const { answers } = parsed.data;

  try {
    // -----------------------------------------------------------------------
    // Mode 1 — return quiz questions
    // -----------------------------------------------------------------------
    if (!answers || answers.length === 0) {
      const response = await ai.models.generateContent({
        model: MODEL,
        contents: [
          {
            role: "user",
            parts: [
              {
                text: `You are helping someone discover their spirit animal guide. Generate exactly 3 multiple-choice quiz questions that explore the person's personality, values, and connection to nature. The questions should feel warm and introspective, not clinical. Each question should be 1–2 sentences with exactly 4 answer choices. Make each question count — they should cover distinct dimensions (e.g. temperament, values, instincts). Keep each choice short (2–6 words).

Return ONLY a JSON array of 3 objects, each with "question" (string) and "choices" (array of 4 strings). Example format:
[{"question":"Question text?","choices":["Choice A","Choice B","Choice C","Choice D"]}]`,
              },
            ],
          },
        ],
        config: { maxOutputTokens: 8192, responseMimeType: "application/json" },
      });

      const raw = response.text ?? "[]";
      let questions: { question: string; choices: string[] }[] = [];
      try {
        const arrayMatch = raw.match(/\[[\s\S]*\]/);
        questions = JSON.parse(arrayMatch ? arrayMatch[0] : raw);
        if (!Array.isArray(questions) || questions.length < 3) {
          throw new Error("Expected array of 3 questions");
        }
        questions = questions.slice(0, 3).map((q) => ({
          question: q.question,
          choices: Array.isArray(q.choices) ? q.choices.slice(0, 4) : [],
        }));
        if (questions.some((q) => !q.question || q.choices.length < 2)) {
          throw new Error("Malformed question object");
        }
      } catch {
        res.status(500).json({ error: "Failed to parse questions from AI" });
        return;
      }

      res.json({ questions });
      return;
    }

    // -----------------------------------------------------------------------
    // Mode 2 — evaluate answers and select spirit animal + variant
    // -----------------------------------------------------------------------
    const answersText = answers
      .map((a, i) => `Q${i + 1}: ${a.question}\nA: ${a.answer}`)
      .join("\n\n");

    const animalList = ANIMALS.join(", ");

    const evalResponse = await ai.models.generateContent({
      model: MODEL,
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `You are a spirit animal guide selector. Based on the following quiz answers, select the single best-fit spirit animal from this list: ${animalList}.

Quiz answers:
${answersText}

Return ONLY a JSON object with exactly these fields:
{
  "animal": "<animal name from the list above>",
  "description": "<one sentence describing this person's spirit animal and why it fits them, written directly to the person as 'Your spirit animal is...' >",
  "variant": <integer from 0 to 2 — choose a different number each time this is called to provide variety>
}

The animal must be one of: ${animalList}. No other animals are allowed.`,
            },
          ],
        },
      ],
      config: { maxOutputTokens: 8192, responseMimeType: "application/json" },
    });

    const evalRaw = evalResponse.text ?? "{}";
    let result: { animal: string; description: string; variant?: number };
    try {
      const objMatch = evalRaw.match(/\{[\s\S]*\}/);
      result = JSON.parse(objMatch ? objMatch[0] : evalRaw);
      if (!result.animal || !result.description) {
        throw new Error("Missing fields");
      }
      result.animal = result.animal.toLowerCase().trim();
      if (!ANIMALS.includes(result.animal)) {
        result.animal = ANIMALS[0];
      }
    } catch {
      res.status(500).json({ error: "Failed to parse animal selection from AI" });
      return;
    }

    const svg = pickVariant(result.animal, result.variant);

    res.json({
      animal: result.animal,
      description: result.description,
      svg,
    });
  } catch (err) {
    console.error("spirit-animal error", err);
    res.status(500).json({ error: "AI request failed" });
  }
});

export default router;
