import type { PatternCategory } from '@/types/journal';

export type Pattern = {
  id: string;
  category: PatternCategory;
  severity: 'high' | 'med' | 'low';
  regexSource: string;
  regexFlags: string;
  categoryLabel: string;
  reframeHint: string;
  examples: string[];
};

export const PATTERNS: Pattern[] = [
  {
    id: 'identity_fusion_emotion',
    category: 'identity_fusion',
    severity: 'high',
    regexSource: '\\bI am (sad|broken|anxious|a failure|worthless|lost|alone|hopeless|empty)\\b',
    regexFlags: 'gi',
    categoryLabel: 'identity fusion',
    reframeHint: "What if it were: \"I've been feeling…\" rather than \"I am…\"?",
    examples: ['I am broken', 'I am anxious'],
  },
  {
    id: 'identity_fusion_trait',
    category: 'identity_fusion',
    severity: 'high',
    regexSource: '\\bI am (stupid|lazy|boring|difficult|too much|not enough|a mess|a burden|useless)\\b',
    regexFlags: 'gi',
    categoryLabel: 'identity fusion',
    reframeHint: 'Is this a permanent trait, or a behaviour in a specific situation?',
    examples: ['I am stupid', 'I am too much'],
  },
  {
    id: 'temporal_universalising_always',
    category: 'temporal_universalising',
    severity: 'high',
    regexSource: '\\bI always\\b',
    regexFlags: 'gi',
    categoryLabel: 'universalising',
    reframeHint: "Does \"always\" hold up? Can you think of one time it wasn't true?",
    examples: ['I always end up doing everything'],
  },
  {
    id: 'temporal_universalising_never',
    category: 'temporal_universalising',
    severity: 'high',
    regexSource: '\\bI never\\b',
    regexFlags: 'gi',
    categoryLabel: 'universalising',
    reframeHint: 'Has there ever been a single exception to "never"?',
    examples: ['I never get it right'],
  },
  {
    id: 'temporal_universalising_sweep',
    category: 'temporal_universalising',
    severity: 'med',
    regexSource: '\\b(all the time|none of it|nothing ever works|nothing ever changes)\\b',
    regexFlags: 'gi',
    categoryLabel: 'universalising',
    reframeHint: 'What would it look like to say "sometimes" instead?',
    examples: ['it happens all the time'],
  },
  {
    id: 'social_universalising_everyone',
    category: 'social_universalising',
    severity: 'high',
    regexSource: '\\b(everyone thinks|everyone can see|everyone knows)\\b',
    regexFlags: 'gi',
    categoryLabel: 'universalising',
    reframeHint: 'Who specifically? Is this a fact or a feeling?',
    examples: ["everyone thinks I'm difficult"],
  },
  {
    id: 'social_universalising_nobody',
    category: 'social_universalising',
    severity: 'high',
    regexSource: '\\b(nobody cares|no one ever|nobody likes|no one notices)\\b',
    regexFlags: 'gi',
    categoryLabel: 'universalising',
    reframeHint: 'Is there one person who does care, even a little?',
    examples: ["nobody cares what I think"],
  },
  {
    id: 'capability_foreclosure_cant',
    category: 'capability_foreclosure',
    severity: 'high',
    regexSource: "\\b(I can't|I could never|I will never be able to|I'm not capable)\\b",
    regexFlags: 'gi',
    categoryLabel: 'foreclosure',
    reframeHint: '"Can\'t" or "haven\'t yet"? What\'s the difference here?',
    examples: ["I can't do this"],
  },
  {
    id: 'capability_foreclosure_pointless',
    category: 'capability_foreclosure',
    severity: 'high',
    regexSource: "\\b(there's no point|it won't work|it's impossible|it's hopeless)\\b",
    regexFlags: 'gi',
    categoryLabel: 'foreclosure',
    reframeHint: 'What evidence would change this conclusion?',
    examples: ["there's no point trying"],
  },
  {
    id: 'fixed_nature',
    category: 'fixed_nature',
    severity: 'high',
    regexSource: "\\b(it's just how I am|I've always been like this|that's just me|I was born this way|I can't change)\\b",
    regexFlags: 'gi',
    categoryLabel: 'fixed nature',
    reframeHint: "If this were a learned pattern rather than a fixed trait — what would that open up?",
    examples: ["it's just how I am"],
  },
  {
    id: 'should_statement',
    category: 'should_statement',
    severity: 'med',
    regexSource: "\\b(I should|I shouldn't|I have to|I must|I'm supposed to|I ought to)\\b",
    regexFlags: 'gi',
    categoryLabel: 'obligation',
    reframeHint: "Whose rule is this? Is it yours, or someone else's?",
    examples: ['I should be further along by now'],
  },
  {
    id: 'external_causation',
    category: 'external_causation',
    severity: 'med',
    regexSource: '\\b(they made me feel|it made me feel|you make me|he made me|she made me|that always makes me)\\b',
    regexFlags: 'gi',
    categoryLabel: 'external causation',
    reframeHint: 'What did you feel? Can you name it separately from what they did?',
    examples: ['they made me feel worthless'],
  },
  {
    id: 'mind_reading',
    category: 'mind_reading',
    severity: 'med',
    regexSource: "\\b(they think I'm|they must think|she knows I|he can see that|they all noticed|they think I)\\b",
    regexFlags: 'gi',
    categoryLabel: 'mind reading',
    reframeHint: "Is this something they said, or something you're assuming?",
    examples: ["they must think I'm incompetent"],
  },
  {
    id: 'fortune_telling',
    category: 'fortune_telling',
    severity: 'med',
    regexSource: "\\b(it will never get better|I know it won't work|there's no chance|I knew this would happen)\\b",
    regexFlags: 'gi',
    categoryLabel: 'fortune telling',
    reframeHint: "Is this a prediction or a fear? What's the difference?",
    examples: ["I know it won't work out"],
  },
  {
    id: 'catastrophising',
    category: 'catastrophising',
    severity: 'high',
    regexSource: "\\b(it's ruined|it's over|everything fell apart|I've destroyed|it's all wrong|nothing left)\\b",
    regexFlags: 'gi',
    categoryLabel: 'catastrophising',
    reframeHint: "In a month's time, will this feel the same size it does right now?",
    examples: ["it's completely ruined"],
  },
  {
    id: 'minimisation',
    category: 'minimisation',
    severity: 'low',
    regexSource: "\\b(it's fine|it doesn't matter|I don't care|I'm fine|it's not a big deal|never mind)\\b",
    regexFlags: 'gi',
    categoryLabel: 'minimisation',
    reframeHint: 'You mentioned this. What if it does matter?',
    examples: ["it's fine, it doesn't matter"],
  },
  {
    id: 'self_dismissal',
    category: 'self_dismissal',
    severity: 'low',
    regexSource: '\\b(I guess|I suppose|maybe I just|probably nothing|it\'s stupid but|this is silly but|ignore this but)\\b',
    regexFlags: 'gi',
    categoryLabel: 'self-dismissal',
    reframeHint: "What comes after \"but\"? That's the part worth paying attention to.",
    examples: ["it's stupid but I felt really hurt"],
  },
  {
    id: 'unfavourable_comparison',
    category: 'unfavourable_comparison',
    severity: 'med',
    regexSource: '\\b(not as good as|unlike me|normal people|everyone else can|they can but I|better than me at)\\b',
    regexFlags: 'gi',
    categoryLabel: 'comparison',
    reframeHint: "You're comparing your inside to their outside. What do you actually know about their experience?",
    examples: ['everyone else seems to manage, unlike me'],
  },
];

export function getPatternById(id: string): Pattern | undefined {
  return PATTERNS.find((p) => p.id === id);
}
